apiVersion: apps/v1
kind: Deployment
metadata:
  name: wechat-pdb
  namespace: zhujq2018
spec:
  selector:
    matchLabels:
      app: wechat-pdb
  replicas: 1
  template:
    metadata:
      labels:
        app: wechat-pdb
    spec:
      containers:
        - name: wechat-pdb
          image: zhujq/wechat
          imagePullPolicy: "Always"
          ports:
            - containerPort: 80
              protocol: TCP
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
            requests:
              cpu: 10m
              memory: 64Mi

